# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development:
  adapter: mysql2
  database: <%= ENV['PAIRWISE_MYSQL_DATABASE'] %>
  username: <%= ENV['PAIRWISE_MYSQL_USER'] %>
  password: <%= ENV['PAIRWISE_MYSQL_PASSWORD'] %>
  pool: 5
  timeout: 5000
  host: <%= ENV['PAIRWISE_MYSQL_HOST'] %>

production:
  adapter: mysql2
  database: <%= ENV.fetch('PAIRWISE_MYSQL_DATABASE') %>
  username: <%= ENV.fetch('PAIRWISE_MYSQL_USER') %>
  password: <%= ENV.fetch('PAIRWISE_MYSQL_PASSWORD') %>
  pool: 5
  timeout: 5000
  port: <%= ENV.fetch('PAIRWISE_MYSQL_PORT') %>
  host: <%= ENV.fetch('PAIRWISE_MYSQL_HOST') %>

test:
  database: pairwise_test